### ISSUE TITLE
wrong file specified in 4chan scraper

### ISSUE THREAD

**Issue by ghost** [saucecode/single_file_scrapers#1]
![Screenshot_20210906-145126_GitHub.png](https://user-images.githubusercontent.com/77245194/132220297-5310127c-55e9-481f-805f-2efc84027d96.png)

this says reddit when it should say 4chan

**Comment by saucecode** [comment]
Thank you, resolved in https://github.com/saucecode/single_file_scrapers/commit/c5bd1e403fb94709f487d700960c7d1d54bc05fe
